### ISSUE TITLE
Make working with shared clients easier

### ISSUE THREAD

**Issue by WillsB3** [splitio/redux-client#112]
## Background / Context

In our application our default Split client is for our `anonymous` traffic type, which we use for logged-out users, e.g. visitors to our marketing website, and visitors to our main application before they've created an account). 

Once a user has created an account and logged in, we send events for and perform experiments using flags with a second `user` traffic type.

I've seen the recently added `selectTreatmentAndStatus` selector which was added to the Redux SDK, however in our app we need to wait on a secondary clients to be ready from within an async action (so we need direct access to the ready promise for the secondary client) which (as far as I can tell) doesn't seem possible using the out of the box API provided by `@splitsoftware/redux-client`.

We have a workaround that uses the `splitSdk` export from `@splitsoftware/splitio-redux` to manually create the secondary client, but the workaround is quite brittle (if, for example someone forgets to use our helper and instead relies on the Redux SDK to automatically instantiate the secondary client in another place in our app, any code using our workaround will fail and hang indefinitely because the client already exists, so our manually maintained `isReady` and `isTimedOut` promises never get resolved/rejected).

## Request

Would you consider exposing the sharedClient map that the Redux SDK maintains internally (along with each clients' ready/timeout promises) so that we do not need to maintain these clients ourselves? Our workaround is causing us quite a few headaches and doesn't feel like a good long-term solution…

## Sample code

For further context and to more clearly illustrate our issue, here's a few snippets of the relevant code for our current workaround 

**getClient.js**
```js
import { splitSdk } from '@splitsoftware/splitio-redux'

/**
 * Our own record of shared clients. The redux SDK already keeps a list of
 * shared clients on `splitSdk.sharedClients` but unless we instantiate the
 * client ourselves we don't have the ability to listen for the `SDK_READY`
 * event using the Redux SDK. The `isReady` property exposed on the Redux state
 * by the Split Redux SDK only tells us if the *main* client is ready.
 */
const sharedClientMap = {}

/**
 * Helper for getting a shared Split client. This should only be used for access
 * to clients that are not the main client (the client created automatically by
 * the Redux SDK when we call `initSplitSdk` in common/store/initSplitSdk.js).
 *
 * If a client for the provided key does not exist, it will be created. Clients
 * are created using the `splitSdk.factory.client` method which means that they
 * automatically have the same configuration as the main client (see
 * common/store/initSplitSdk.js).
 *
 * @param {string} key Identifier for the the user (e.g. user._id for the client
 *  for the `user` traffic type).
 * @param {Object} options
 * @param {Function} options.setClientState Optional function which will be
 *  called with the new client state when the client is ready or times out. The
 *  intention is that the function passed here is a setState function from
 *  React's useState hook.
 * @returns {{client: Object, isReady: Promise<void>}} An object containing the
 *  Split client and a promise that resolves when the client is ready.
 */
export const getClient = (key, { setClientState } = {}) => {
  if (sharedClientMap[key]) return sharedClientMap[key]

  if (!splitSdk.factory) {
    throw new Error(
      'Ensure Split SDK has been initialised before calling getClient'
    )
  }

  const client = splitSdk.factory.client(key)

  sharedClientMap[key] = {
    client,
    isReady: false,
    isReadyPromise: new Promise((resolve) => {
      client.on(client.Event.SDK_READY, () => {
        resolve()

        const state = {
          ...sharedClientMap[key],
          isReady: true,
          isTimedOut: false,
        }

        sharedClientMap[key] = state

        if (setClientState) {
          setClientState(state)
        }
      })
    }),
    isTimedOut: false,
    isTimedOutPromise: new Promise((resolve) => {
      client.on(client.Event.SDK_READY_TIMED_OUT, () => {
        resolve()

        const state = {
          ...sharedClientMap[key],
          isReady: false,
          isTimedOut: true,
        }

        sharedClientMap[key] = state

        if (setClientState) {
          setClientState(state)
        }
      })
    }),
  }

  return sharedClientMap[key]
}

```

In our Redux async action we're then using `getClient` like this:

**actionCreators.js**

```js
export const submitAnswers = () => async (dispatch, getState) => {
  const state = getState()
  const userId = getUser(state)._id
  const FLAG_NAME = 'ExptMyFlag'
  const { isReadyPromise, isTimedOutPromise } = getClient(userId)

  // Wait for the secondary client for our `user` traffic type to be ready,
  // as we need it to get the treatment to know if we should show the modal.
  await Promise.race([isReadyPromise, isTimedOutPromise])
  await dispatch(
    getTreatments({
      key: userId,
      splitNames: [FLAG_NAME],
    })
  )
  // Refetch state so we can retrieve the treatment that the Split SDK will
  // have now set.
  const newState = getState()
  const treatment = selectTreatmentValue(newState.splitio, FLAG_NAME)

  if (treatment === 'experiment_variant') {
    const ExperimentModal = (await import('ui/common/ExperimentModal')).default
    dispatch(showModal({ component: ExperimentModal }))

    // We're showing the modal, so early return so we don't perform any other
    // actions.
    return
  }

  return dispatch(submitAnswers())
}
```

**Comment by WillsB3** [comment]
I think it would be really helpful if the Redux SDK exposed all clients states in the `splitio` redux Slice as that would probably remove the need for weird workarounds like the one above^.

I know that a snapshot of the current status of a secondary client can be retrieved via the `selectTreatmentAndStatus` selector but if I understand the code correctly since the `status` is not actually exposed in redux changes to the secondary client ready state do not cause components using the `selectTreatmentAndStatus` to re-render (please correct me if I'm wrong…)

**Comment by EmilianoSanchez** [comment]
Hi @WillsB3 , 

Sorry for the delay in addressing this issue and for the inconveniences you’ve experienced with the Redux SDK.

You are correct regarding the `splitio` redux slice :). We plan to extend the `splitio` slice to expose all client's states and solve issue #113 as you mention. But we don't have an ETA yet. 

In the meantime, there are 2 other SDK client methods that you could consider for your workarounds:

- 1. Client `ready` promise:

```typescript
import { splitSdk, splitReducer, ... } from '@splitsoftware/splitio-redux'

splitSdk.factory.client().ready().then(() => {
  // client `isReady` status is true
}).catch(() => {
  // client `isTimedout` status is true 
});

// for non-default clients:
splitSdk.sharedClients[NON_DEFAULT_KEY].ready();
```

More details about the `ready` promise behavior are available in the JS SDK typescript definition comments: https://github.com/splitio/javascript-client/blob/development/types/splitio.d.ts#L439

- 2. Client `__getStatus` method:

This is a "private" method, in the sense that it is not exposed via typescript definitions, but you can use it to retrieve the status of the client, very similar to the `getStatus` helper function from the Redux SDK:

```typescript
import { splitSdk, splitReducer, ... } from '@splitsoftware/splitio-redux'

type Status = {
  isReady: boolean,
  isReadyFromCache: boolean,
  hasTimedout: boolean,
  isDestroyed: boolean
}

// @ts-expect-error
const clientStatus = splitSdk.sharedClients[NON_DEFAULT_KEY].__getStatus() as Status;
```

On the next release, it will include `isTimedout` and `lastUpdate` properties, to be consistent with the return object of Redux SDK `getStatus` helper.

**Comment by EmilianoSanchez** [comment]
Closing the issue now that version 1.14.0 of the SDK has been released, which includes fixes for handling events of non-default clients.

More info [here](https://github.com/splitio/redux-client/issues/113#issuecomment-2350173172).
