### ISSUE TITLE
Split reducer throws exception if payload is `null`.

### ISSUE THREAD

**Issue by WillsB3** [splitio/redux-client#121]
Hey,

I've just found an issue that occurs when dispatching an action where `payload` is `null`.

One of our applications actions does this and it's causing the Split reducer to throw an exception, even though the action is unrelated to Split. It occurs when the Split reducer tries to read the `timestamp` property of `payload` (which is `null`).

Please see attached screenshots that show the Split reducer throwing an exception when our application dispatches a  `SET_REDEMPTION_PARTNER_DETAILS` action with `payload` of `null`.

This behaviour was observed using version 1.14.0 of the Redux SDK.

![Screenshot 2024-10-14 at 12 34 18](https://github.com/user-attachments/assets/b2c3801e-741b-4dda-b7e3-86e45343c5a3)
![Screenshot 2024-10-14 at 12 33 42](https://github.com/user-attachments/assets/8f083b4d-331a-4a15-9f35-61a577c87355)

**Comment by EmilianoSanchez** [comment]
Hi @WillsB3 , 

Thank you for catching that. I will release a fix ASAP, along with a corresponding test to prevent any regression.

**Comment by EmilianoSanchez** [comment]
FYI @WillsB3 , Redux SDK v1.14.1 was released with a fix. 

As you noticed, version 1.14.0 introduced a bug on `splitReducer` which was accessing action payload properties before checking the action type.

I will close the issue for now, but feel free to reopen it or create a new one if you find any related issues. 
Thanks!

**Comment by WillsB3** [comment]
Thanks for the quick fix @EmilianoSanchez 🙏
