### ISSUE TITLE
Expose addTreatments so that it can be used in tests

### ISSUE THREAD

**Issue by TheManWhoStaresAtCode** [splitio/redux-client#67]
Hi there.

we typically test our React components that are connected to the redux store with the actual store in place. In order to setup the store we trigger the respective actions and then we can assert the expected behavior of our component. However, when we want to test that a component is displayed when a feature is on and another component when the feature if off, we cannot use the addTreatments action as it is not part of the exports in the index.ts file. In former versions (e.g. 1.4.0) it was possible to import the action anyhow but that breaks now when upgrading to the latest version 1.7.1.

I think that is fine as we where using a non public API and thus it is not you fault but would it be possible for you to also expose the addTreatments action? I might also provide the PR for doing so but I want to get your feedback first.

Best regards.

**Comment by hbqdev** [comment]
Hi @TheManWhoStaresAtCode 

Can you please clarify what you mean by expose the addTreatment action?

Thank you and Regards

**Comment by TheManWhoStaresAtCode** [comment]
Hi @hbqdev 

I want to have an export in the index.ts file that exports this action.

Best regards

**Comment by hbqdev** [comment]
Hi @TheManWhoStaresAtCode 
Thank you for the information, we have submitted this request to our PM. You can check our change logs for future updates.

Thank you and Regards

**Comment by EmilianoSanchez** [comment]
Hi @TheManWhoStaresAtCode , 

If it is the case that you were importing the `addTreatments` action via its absolute path, like `import { addTreatments } from '@splitsoftware/splitio-redux/es/actions'`, it should still be working in v1.7.1, because there aren't changes between 1.4.0 and 1.7.1 regarding that internal export. But be aware that we might eventually rename the file or change the action location, without previous notice, since it is not considered part of the library public API yet.

**Comment by TheManWhoStaresAtCode** [comment]
Hi @EmilianoSanchez,

you are right that in pure JS everything works as expected. However, between 1.4.0 and 1.7.1 the location of the TypeScript types has changed and, thus now either the TypeScript compiler complains about the imports if I use the import you suggested or the code fails on runtime if I use `import { addTreatments } from '@splitsoftware/splitio-redux/types/actions'` which makes the compiler happy. 

Anyhow, as you stated you do not consider it as part of the public API of the library we will think about another solution like mocking the respective calls to not depend on library internas. Thanks for the clarification.

**Comment by EmilianoSanchez** [comment]
I see it now, @TheManWhoStaresAtCode . Maybe a `// @ts-ignore` comment right above the import can help to avoid the TSC complain, or by indicating that the declaration file is located in `@splitsoftware/splitio-redux/types/actions`.

Thanks for the comments!
